Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Max: 101

Metrics/AbcSize:
  Exclude:
   - 'main.rb'

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 11
